# ! JUST READ - don't change the content of this file
# Server settings with final resolved parameters
# (includes sd_server() parameters, YAML header, and defaults)
use_cookies: yes
auto_scroll: yes
rate_survey: no
all_questions_required: no
system_language: cs
highlight_unanswered: yes
highlight_color: blue
capture_metadata: yes

